oxherding_full_text = [
    "one aimlessly pushes the grasses",
    "aside in search",
    "the rivers are wide",
    "the mountains far away",
    "and the path becomes longer",
    "exhausted and dispirited",
    "one hears only the late autumn cicadas",
    "shrilling in the maple woods",
    "by the water, and under the trees",
    "there are numerous traces",
    "fragrant grasses grow thickly",
    "but did you see the ox?",
    "even in the depths",
    "of the distant mountain forest",
    "how could the upturned nostrils",
    "of the ox be concealed?",
    "a bush warbler sings upon a branch",
    "warm sun, soft breezes",
    "green willows on the bank",
    "nowhere can the ox escape to hide",
    "but those majestic horns",
    "are difficult to draw",
    "with all my energy",
    "i seize the ox",
    "his will is strong, and his power endless",
    "and he cannot be tamed easily",
    "sometimes he charges",
    "to the high plateau",
    "and there he stays",
    "deep in the mist",
    "one does not let go of the whip or the rope",
    "afraid it will stray",
    "and choose the dusty mist",
    "a well-tended ox becomes gentle",
    "and even with no rope",
    "will follow people",
    "by himself",
    "riding the bull, i leisurely",
    "wander toward home",
    "exotic flute melodies echo",
    "through sunset clouds",
    "each beat and each tune",
    "is indescribably profound",
    "no words are needed for those",
    "who understand music",
    "riding on the ox",
    "he has come home",
    "there is no ox there",
    "and he is at ease",
    "although the sun is high",
    "he is still dreamy",
    "the whip and rope abandoned",
    "in the thatched hut",
    "whip, rope, man, and ox",
    "all are non-existent",
    "the blue sky being vast",
    "no message can be heard",
    "just as the snowflake cannot last",
    "in the flaming red furnace",
    "after this state, one can join",
    "the ancient teachers",
    "in returning to the fundamentals",
    "and going back to the source",
    "i had to work so hard",
    "perhaps it would be better",
    "to be blind and deaf",
    "being in the hut",
    "i do not see what is outside",
    "the river flowing tranquilly",
    "the flower simply being red",
    "he enters the city barefoot",
    "with chest exposed",
    "covered in dust and ashes",
    "smiling broadly",
    "no need for the magic powers",
    "of the gods and immortals",
    "just let the dead tree bloom again",
]
