graph LR
    ngondro-->four-thoughts
    four-thoughts-->precious-life
    precious-life-->six-realms
    four-thoughts-->impermanence
    four-thoughts-->karma
    four-thoughts-->suffering
    meditations-->support
    support-->breath
    support-->thought
    meditations-->imaginative
    imaginative-->animal
    imaginative-->buddha