graph LR

    books-->mingyur-rinpoche
    books-->dudjom-lingpah
    books-->zen-felsh-zen-bones
    mingyur-rinpoche-->confusion-to-clarity
    confusion-to-clarity-->ngondro
    dudjom-lingpah-->alan-wallace-translation
    dudjom-lingpah-->dhogzhen
